# Site settings
course_name: "STAT 548R: Seminar on Effective Research Skills"
course_title: "STAT 548R: Seminar on Effective Research Skills"
course_semester: "Fall 2025 (2025-WT1)"

baseurl: "/stat-548r" # the subpath of your site, e.g. /blog/
url: "http://ubc-stat.github.io/" # the base hostname & protocol for your site

schoolname: "University of British Columbia"
schoolurl: ""

address: |
    Department of Statistics
    University of British Columbia

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
